### ISSUE TITLE
Testing Bug: Chrome Console errors

### ISSUE THREAD

**Issue by DMASCoreDeclan** [DMASCoreDeclan/PRD-PP4-Blog#46]
Uncaught TypeError: Cannot read properties of undefined (reading 'classList')
    at Ie._isAnimated (modal.js:333:26)
    at Ie._initializeBackDrop (modal.js:206:24)
    at new Ie (modal.js:84:27)
    at script.js:1:25
_isAnimated @ modal.js:333
_initializeBackDrop @ modal.js:206
Ie @ modal.js:84
(anonymous) @ script.js:1

**Comment by DMASCoreDeclan** [comment]
_Uncaught TypeError: Cannot read properties of undefined (reading 'classList') **- Bootstrap CDN .js file - won't fix this**
at Ie._isAnimated (modal.js:333:26) **- Bootstrap CDN .js file - won't fix this**
at Ie._initializeBackDrop (modal.js:206:24) **- Bootstrap CDN .js file - won't fix this**_
_at new Ie (modal.js:84:27) **- Bootstrap CDN .js file - won't fix this**_
**at script.js:1:25** **- fixed in project .js**
__isAnimated @ modal.js:333 **- Bootstrap CDN .js file - won't fix this**
_initializeBackDrop @ modal.js:206 **- Bootstrap CDN .js file - won't fix this**
Ie @ modal.js:84 **- Bootstrap CDN .js file - won't fix this**_
**(anonymous)** @ script.js:1 **- fixed in project .js file**

**Comment by DMASCoreDeclan** [comment]
As a result of fixing:

It is replaced by this error:
Uncaught TypeError: Class constructor Ie cannot be invoked without 'new'
    at script.js:1:35

I'm putting "new" back ,.js

These lines will return
**at script.js:1:25** **- unfixed in project .js**
**(anonymous)** @ script.js:1 **- unfixed in project .js file**

**Comment by DMASCoreDeclan** [comment]
On advice from Mentor, the problem was that script.js was being loaded where it could not work.

It was part of the base.html <script> section.
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
       <script src="{% static 'js/script.js' %}" defer></script>
</script>

We created a 
{% block extras %}
{% endblock extras%}
in base.html

and in the required pages, where a delete confirmation was required, we entered
{% block extras %}
    <script src="{% static 'js/script.js' %}" defer></script>
{% endblock extras%}

The error no longer appears
